# Generated by Django 4.1.1 on 2022-11-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduworld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfassignments',
            name='descrição',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfassignments',
            name='titulo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
