# Generated by Django 4.1.1 on 2022-11-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduworld', '0005_pdfassignments_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfassignments',
            name='status',
            field=models.CharField(choices=[('Submitted, Graded', 'Submitted, Graded'), ('Submitted', 'Submitted'), ('Not submitted yet', 'Not submitted yet')], default='Not submitted yet', max_length=26),
        ),
    ]
