# Generated by Django 4.1.1 on 2022-11-16 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduworld', '0007_statusaluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfassignments',
            name='status',
        ),
        migrations.AlterField(
            model_name='statusaluno',
            name='status',
            field=models.CharField(choices=[('Submitted, Graded', 'Submitted, Graded'), ('Missed', 'Missed'), ('Not submitted yet', 'Not submitted yet')], default='Not submitted yet', max_length=26),
        ),
    ]
