# Generated by Django 4.1.1 on 2022-11-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduworld', '0008_remove_pdfassignments_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfassignments',
            name='due_hour',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
