# Generated by Django 4.1.1 on 2022-11-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduworld', '0009_pdfassignments_due_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfassignments',
            name='points',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
