# Generated by Django 4.1.1 on 2022-11-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduworld', '0010_pdfassignments_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusaluno',
            name='grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
