# Generated by Django 4.1.1 on 2022-11-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduworld', '0011_statusaluno_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusaluno',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
