# Generated by Django 4.1.1 on 2022-11-17 21:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduworld', '0012_statusaluno_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusaluno',
            name='status',
            field=models.CharField(choices=[('Submitted, Graded', 'Submitted, Graded'), ('Submitted', 'Submitted'), ('Missed', 'Missed'), ('Not submitted yet', 'Not submitted yet')], default='Not submitted yet', max_length=26),
        ),
        migrations.CreateModel(
            name='PrivateComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aluninho', to=settings.AUTH_USER_MODEL)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atvd', to='eduworld.pdfassignments')),
            ],
        ),
    ]
