# Generated by Django 4.1.1 on 2022-11-17 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduworld', '0013_alter_statusaluno_status_privatecomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatecomments',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
