# Generated by Django 4.1.1 on 2022-11-18 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduworld', '0014_privatecomments_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatecomments',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
