# Generated by Django 4.1.1 on 2022-11-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduworld', '0016_statusaluno_data_de_envio'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusaluno',
            name='gradeLetter',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
