# Generated by Django 4.1.1 on 2022-11-26 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduworld', '0017_statusaluno_gradeletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatecomments',
            name='has_reply',
            field=models.BooleanField(default=False),
        ),
    ]
