# Generated by Django 4.1.1 on 2022-11-26 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduworld', '0019_replyprivatecomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='replyprivatecomments',
            name='atividade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='atvdm', to='eduworld.pdfassignments'),
            preserve_default=False,
        ),
    ]
