# Generated by Django 4.1.1 on 2022-11-29 12:33

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduworld', '0020_replyprivatecomments_atividade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_text', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('data', models.DateTimeField(default=datetime.datetime.now)),
                ('reply_count', models.BigIntegerField(default='0')),
                ('views', models.BigIntegerField(default='0')),
                ('category', models.CharField(blank=True, max_length=300, null=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DONO_DO_POST_FORUM', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
