# Generated by Django 4.1.1 on 2022-12-01 18:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduworld', '0023_replyforumcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replyforumcomments',
            name='texto',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
