# Generated by Django 4.1.1 on 2022-12-01 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eduworld', '0024_alter_replyforumcomments_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='replyforumcomments',
            name='dono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='DONO_DO_RESOPSTA', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
